.github/ISSUE_TEMPLATE/config.yml

Let users, when creating an issue on GitHub, select two more options:
1. Blank issue (no template, option pretty "hidden")
2. Ability to join Discord from right there.

Added more option at issue creation process

---

CODE_OF_CONDUCT.md

When having Discussions enabled on a GitHub repository, it's important to have rules—just like on any public board. CODE_OF_CONDUCT.md provides just that.

Code of Conduct due to additions of "Discussions"

---

src/20H2/AtlasModules/atlas-config.bat

If a user tries to run a script that disables Store or UWP while having a Microsoft Account on their computer, the wlidsvc will not be disabled so they can sign in.
I also added a disable UAC warning.

Add support for Microsoft Accounts for UWP and Store + UAC disable warning

---

src/20H2/AtlasModules/atlas-config.bat

This sets UAC level to the default settings of notifying you only when applications try to make changes to your computer.

Set enable UAC script to set the default level

---

src/20H2/AtlasModules/atlas-config.bat
src/20H2/Desktop/Atlas/3. Configuration/FSO & Gamebar/Disable FSO & Gamebar (default).reg
src/20H2/Desktop/Atlas/3. Configuration/FSO & Gamebar/Enable FSO & Gamebar.reg

This adds the `__COMPAT_LAYER` environment variable to set the 'Disable full-screen optimisations' compatibility flag globally on every application, ensuring that full-screen optimisations are disabled.
https://stackoverflow.com/questions/37878185/what-does-compat-layer-actually-do/37881453#37881453

Add "__COMPAT_LAYER" to disable FSO

---

src/AtlasModules/atlas-config.bat

This sets certain applications (serviwin, DevManView, nsudo, pssuspend and vcredist), which usually require UAC, to always run as administrator.

Make Utilities Request UAC

---

src/AtlasModules/README.md

The verification information for `vcredist.exe` was not updated, this pull request fixes that.

Update Verification Info

---

src/AtlasModules/atlas-config.bat

- Starts explorer.exe as the current user correctly
- Kills explorer.exe multiple times in case there's multiple instances
- Finds the container (for the icon) for older NVIDIA drivers

Fix Display Container Context Menu

---

.gitattributes

Create .gitattributes to make sure that all batch scripts are using CRLF (Windows) line endings. With any other line endings, batch labels and many other things get broken.

Fix line endings on all batch scripts

---

src/AtlasModules/atlas-config.bat

- Shortens length of `reg` commands by shortening `HKEY_LOCAL_MACHINE` to `HKLM` (as an example)
- More readable
- Use a variable `%currentuser%` instead of repeating the whole NSudo command for admin elevation
- Change `echo.` to `echo]`, just in case a user has a different `echo.exe` in PATH or the current directory
- Add new `setSvc` function, which cleans up the services/drivers part a lot and does checks
- Make disabling scheduled tasks a for loop so it's more readable and cleaner
- Add `firewallBlockExe` function to more improve blocking of executables in the firewall

Clean up atlas-config

---

src/Atlas_20H2.xml

Some older games, for example games from the Gothic series, can't run without that component of windows being present.

Improve compatibility with older games

---

src/AtlasModules/atlas-config.bat

Updated the download URL to the latest official Scoop install.ps1 script. Added -RunAsAdmin flag so that scoop will install when the script is run as Administrator (which it is in the current version of AtlasOS).

Fix scoop error when using 1. Install Software

---

src/AtlasModules/atlas-config.bat

Calling PowerShell from batch in a loop is expensive, mitigations can be disabled in the form of a list.
1) I was unable to find a method of reducing this code block to a single call (mentioning it here as it is related).
```bat
:: enable cfg for valorant related processes
for %%i in (valorant valorant-win64-shipping vgtray vgc) do (
PowerShell -NoProfile -Command "Set-ProcessMitigation -Name %%i.exe -Enable CFG"
)
```
2) The code under the ``:mitE`` function could be placed in a separate function as the same line is repeated in the hardening section but I did not include it in this PR as I was not sure if this was intentional.

Reduce PowerShell calls

---

src/AtlasModules/atlas-config.bat

This PR effectively cuts the MSI portion runtime in half because two loops were used to get the same data from WMI.
As MSI/IRQ priorities take effect after a reboot, network adapters can be set to undefined unconditionally then set to normal if the system is a VM rather than including an unnecessary check; ``if (VM) {normal} else {undefined}``.

Condense MSI portion

---

src/AtlasModules/atlas-config.bat

Hi,
OneDrive is already removed via NTLite in `Atlas_20H2.xml` and so on. So these lines to disable OneDrive is actually not necessary.
The original registry change cannot either remove OneDrive or prevent it from installing. But if someone wants to install OneDrive, this will block him from start OneDrive.
So the change here fix the bug that manual OneDrive installation could not run.

re-enable onedrive, which allow user to re-install onedrive if need

---

src/AtlasModules/atlas-config.bat
src/Desktop/Atlas/1. Install Software/Install.ps1

Hi,
This PR include 3x changes:
1. I build an image myself and installed it, but find install software not successful with a prompt from NSudo that it's not elevated. So I change the paramater of NSudo from `-U:C` to `-U:E` which will use elevated user instead of current user.
2. scoop and chocolatey are actually installed via `atlas-config.bat`. So we can remove `src/Desktop/Atlas/1. Install Software/Manual/Install Chocolatey.bat` and `src/Desktop/Atlas/1. Install Software/Manual/Install Scoop.bat` since they are never used.
3. I find git is installed during scoop / choco installation which is introduced in 1f064b96979ed5a65d140dbd096d33fb37836fcc, but it's not a necessary step to install scoop or choco. So I remove it. As I tested it does not break anything.

fix software install unsuccessful due to nsudo not elevated

---

src/AtlasModules/atlas-config.bat

This PR removes unnecessary handling of write cache:
The image above is the default setting of write cache. Value of 1 for each registry entry means checked in coresponding checkbox.
- `CacheIsPowerProtected` stands for `Enable write caching on the device`. Checking this box will enable cache on disk (usually DRAM of HDD/SSD not but NAND of SSD or disk of HDD) which enable higher performance.
- `UserWriteCacheSetting` is related to caching mechanism of Windows. With this boxed checked, Windows will automatically flush cached IO to disk, so that even if an application does not flush data to disk itself, Windows could still try to keep data safe with its flush mechanism.
So these lines have two problems:
1. The comment says it's disabling write cache but it's actually enabling write cache. …

remove disable of write cache flush which may leads to data loss

---

README.md
translations/README.md

Fixed typo (available)
Fixed Deutsch subtext to Turkish
Added Turkish option and flag to available translations under Translation page

Quick fix about translation page

---

src/Atlas.bat
src/AtlasModules/atlas-config.bat
src/Desktop/Atlas/1. Install Software/Cleanup Scoop Cache (after installing any software via Scoop).bat
src/Desktop/Atlas/3. Configuration/Animations/Disable Animations (default).bat
src/Desktop/Atlas/3. Configuration/Animations/Enable Animations.bat
src/Desktop/Atlas/3. Configuration/Background Apps/Disable Background Apps (default).bat
src/Desktop/Atlas/3. Configuration/Hyper-V and VBS/Disable Hyper-V and VBS (default).bat
src/Desktop/Atlas/3. Configuration/Hyper-V and VBS/Enable Hyper-V and VBS.bat
src/Desktop/Atlas/3. Configuration/Microsoft Store/Disable Microsoft Store.bat
src/Desktop/Atlas/3. Configuration/Microsoft Store/Enable Microsoft Store (default).bat
src/Desktop/Atlas/3. Configuration/Notifications/Disable Notifications (default).bat
src/Desktop/Atlas/3. Configuration/Notifications/Enable Notifications.bat
src/Desktop/Atlas/3. Configuration/Search Indexing/Disable Search Indexing (default).bat
src/Desktop/Atlas/3. Configuration/Search Indexing/Enable Search Indexing.bat
src/Desktop/Atlas/3. Configuration/Start Menu/Disable Start Menu and Search.bat
src/Desktop/Atlas/3. Configuration/Start Menu/Enable Start Menu and Search.bat
src/Desktop/Atlas/3. Configuration/Start Menu/Install Open-Shell (run first).bat
src/Desktop/Atlas/3. Configuration/Start Menu/Unlock Start Menu Tiles.bat
src/Desktop/Atlas/3. Configuration/UWP/Install Open-Shell (run first).bat
src/Desktop/Atlas/3. Configuration/Wi-Fi/Disable Wi-Fi.bat
src/Desktop/Atlas/3. Configuration/Wi-Fi/Enable Wi-Fi (default).bat
src/Desktop/Atlas/3. Configuration/Workstation (SMB)/Disable Lanman Workstation (default).bat
src/Desktop/Atlas/3. Configuration/Workstation (SMB)/Enable Lanman Workstation.bat
src/Desktop/Atlas/4. Advanced Configuration/NVIDIA/Force P-State 0/NVIDIA Force P-State 0.bat
src/Desktop/Atlas/4. Advanced Configuration/NVIDIA/Force P-State 0/Revert NVIDIA Force P-State 0.bat

Makes them easier to add to and read. Also makes the scripts have the same argument as the labels, so it is more simple.

Simplify atlas-config args

---

src/AtlasModules/atlas-config.bat
src/Desktop/Atlas/3. Configuration/Bluetooth/Disable Bluetooth (default).bat
src/Desktop/Atlas/3. Configuration/Bluetooth/Enable Bluetooth.bat
src/Desktop/Atlas/3. Configuration/Send To Debloater.cmd
src/Desktop/Atlas/Optional Tweaks/User Interface/Windows Explorer Customization/Removable Drives in Sidebar/Disable Removable Drives in Sidebar (default).reg
src/Desktop/Atlas/Optional Tweaks/User Interface/Windows Explorer Customization/Removable Drives in Sidebar/Enable Removable Drives in Sidebar.reg

- Fixes Hyper-V enable script
- New 'Send To' debloat script using `multichoice.exe`
- Debloated 'Send To' context menu by default
- Reverts deleting 'Power saver' power plan (for laptops) and doesn't replace 'High Performance' power plan
- Improve notifications scripts
- Disable removable drives in Explorer sidebar by default (includes `.reg` files to toggle)
- Your drives are all in 'This PC'

'Send To' debloat script & general improvements/fixes

---

src/AtlasModules/atlas-config.bat

This PR include two changes:
1. When removing lower filters for rdyboost, it affects other storage volumes LowerFilters. In default installation, they are fvevol & iorate. With 3rd party drivers, there would be more. The change is to have only rdyboost removed.
2. I checked removval of service dependencies. With stock settings, `Dhcp` DependOnService is NSI & Afd, `Dnscache` DependOnService is NSI & Afd, `rdyboost` DependOnService is nothing. So those 3 lines of removal actually have no effects at all. Thus those lines are removed.

revise on REG_MULTI_SZ changes

---

src/AtlasModules/atlas-config.bat

This PR include 2x cleanup:
1. modification to ntp server don't require service restart, as `w32tm /config /update` in next line will do the update. I captured ntp frames via Wireshark could prove so,
2. since W32Time is disabled and we'll restart system at the end, we also don't need to stop it in script.

remove unnecessary start and stop of ntp service

---

src/AtlasModules/atlas-config.bat

by default, service `w32time` is started manually. so lines of `w32tm /config /update` & `w32tm /resync` always report an error that the service is not started. this pr add a line to start the service.

start ntp before time sync since its default start type is manual

---

src/AtlasModules/atlas-config.bat

This PR includes 2x changes:
Disable notification lines are removed since they are not necessary. This feature is always enabled in every supported version of Windows, and post-install script is always executed immediately after system installation. So we don't need to be sure of anything.
Seeting powershell execution policy to unretricted is also removed because:
1. this line does not work at all, `%PowerShell%` here will be expanded with https://github.com/Atlas-OS/Atlas/blob/99a596bfd92e4d2ed58e84adbd3b30eac56bc8bc/src/AtlasModules/atlas-config.bat#L38 to `C:\Windows\System32\WindowsPowerShell\v1.0\PowerShell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "Set-ExecutionPolicy Unrestricted -Force"`. And there would be an error since execution policy is set twice in this …

remove ps execution policy setting and trim setting

---

src/AtlasModules/atlas-config.bat

There are two lines toggling Virtualization-based Security but with typo error. Another line is right: https://github.com/Atlas-OS/Atlas/blob/f07849fdd9db54ad6932da4a7008c7eb5e288560/src/AtlasModules/atlas-config.bat#L1774
By the way, by checking microsoft documents, it looks this switch should not affect enable / disable of Hyper-V at all. Maybe we could remove these lines?

fix typo for Virtualization-based Security

---

src/AtlasModules/atlas-config.bat

Changing`https://raw.githubusercontent.com/ScoopInstaller/install/master/install.ps1` 
to `https://cdn.jsdelivr.net/gh/ScoopInstaller/Install@master/install.ps1`
-`https://raw.githubusercontent.com` is restricted to access / slow to access in certain regions and ISP's. 
(e.g. China, [India (Jio Network) ](https://github.com/anuraghazra/github-readme-stats/issues/2446#issuecomment-1399228965))

change Scoop link to JsDelivr

---

src/README.md

tb.rg-adguard.net is no longer updated. They recommend files.rg-adguard.net but you have to use torrents. Instead, replace the link with Fido.

Change tb.rg-adguard.net to Fido

---

README.md

Now, the language list follows an alphabetical order of the English names of the sovereign countries.
I also changed the native language name for Brazil (currently it's the Brazilian Portuguese name of Brazil - "Brasil"), Italia (from "Italia" to "Italiano", the native name), Philippines, and Ukraine.
All of the names were taken from the English Wikipedia.
The list now follows this order:
<details><spoiler>
```
Bosnia and Herzegovina
Brazil
China
France
Germany
India
Indonesia
Italy
Philippines
Poland
Russia
Saudi Arabia
Spain
Sweden
Turkey
Ukraine
Vietnam
```
</spoiler></details>

Update language list in README.md

---

src/playbook/Executables/AtlasDesktop/3. Configuration/Start Menu/Install Open-Shell.cmd
src/playbook/Executables/AtlasDesktop/6. Advanced Configuration/Utilities/Process Explorer/Install and Replace Task Manager.cmd

Adds Winget error checking in the `Install Open-Shell` and `Install and Replace Task Manager` scripts
This fixes [v03-testing > Install Open-shell script error](https://ptb.discord.com/channels/795710270000332800/1149430331913543770)

Add Winget Error Checking to Scripts

---

src/playbook/Executables/AtlasDesktop/1. Software/Remove Edge.ps1
src/playbook/Executables/AtlasModules/Scripts/Modules/Uninstall-MsiexecAppByName/Uninstall-MsiexecAppByName.psm1
src/playbook/Executables/CLEANUP.ps1
src/playbook/Executables/LIBREWOLF.ps1
src/playbook/Executables/SOFTWARE.ps1

Fixes error out output redirection which causes the script to freeze
Fixes playbook freeze (reticulating splines) when removing Edge due to an error in output redirection in powershell command

Update Remove Edge.ps1

---

src/playbook/Executables/AtlasDesktop/3. Configuration/Power/Standby States/Disable Standby States (default).cmd

Fixes bug: the script is called with "silent" parameter not "setup"
The script is being paused because it's checking for the wrong parameter. This fixes that

Update Disable Standby States (default).cmd

---

src/playbook/Executables/AtlasModules/Scripts/RunAsTI.cmd

Fixed Delayed Variable Expansion, addressed issue where program_path variable would not be parsed until the if loop was completed.

Fix: RunAsTI.cmd

---

src/playbook/Executables/SOFTWARE.ps1

Changes to using "NewGuid" instead of "GetRandomFileName" as 'GetRandomFileName' has 2^56 possible combinations vs the 2^122 possible combinations with 'NewGuid'. Very minor and redundant but still an improvement

Update SOFTWARE.ps1 to use NewGuid

---

src/playbook/Executables/SOFTWARE.ps1

SOFTWARE.ps1: Fix VLC Download

---

src/playbook/Executables/AtlasDesktop/1. Software/How To Install Software.url

This will fix https://github.com/Atlas-OS/Atlas/issues/1056

Fix: Invalid shortcut to  docs "post-installation/software/getting-started" in AtlasDesktop

---

src/playbook/Configuration/atlas/services.yml
src/playbook/Configuration/tweaks/misc/enable-notifications.yml
src/playbook/Configuration/tweaks/qol/windows-update/disable-auto-updates.yml
src/playbook/Configuration/tweaks/scripts/script-core-isolation.yml
src/playbook/playbook.conf

- The page related to services has been removed
- Many users go through the options without reading
- This leads to them disabling functionality that they then can't re-enable in the usual ways in Windows, which causes confusion
- This is all for a very negligible performance boost
- Disabling notifications is a security risk as users can't get [update notifications](https://docs.atlasos.net/getting-started/post-installation/atlas-folder/general-configuration/#automatic-updates)
- Auto-updates and core isolation have swapped places
- Auto-updates is now a radio page and provides more info on updates
- Info on core isolation is arguably less critical than info on auto-updates
- Mitigations has had its TopLine (the grey text underneath) swapped with the description
- This is to make users …

feat: refactor Playbook options

---

src/playbook/Configuration/atlas/start.yml
src/playbook/Executables/CLEANUP.ps1

Disables cleaning the component store and Windows Update in Disk Cleanup (`cleanmgr`) as I'm guessing this causes DISM to randomly hang when changing features.

fix: clean component store after optional features

---

src/playbook/Executables/AtlasDesktop/6. Advanced Configuration/Services/Notifications/Disable Notifications.cmd

Adds info and a prompt to the user about the security implications of disabling notification services.
> Disabling notifications means **all** notifications, including system ones.
> This includes notifications that notify you about security updates.
> 
> This doesn't improve performance.
> 
> ---
> 
> Would you like to continue anyways? [Y/N]

feat: add security warning for disabling notifications

---

src/playbook/Configuration/tweaks.yml
src/playbook/Configuration/tweaks/qol/disable-screen-capture-hotkey.yml
src/playbook/Configuration/tweaks/qol/ease-of-access/disable-annoying-features-shortcuts.yml

-disable narrator keyboard shortcut
-disable print screen key opening screen capture when snipping tool is removed

feat: disable narrator and screen capture shortcuts

---

src/playbook/Configuration/tweaks.yml
src/playbook/Configuration/tweaks/performance/respect-power-modes-search.yml
src/playbook/Executables/AtlasDesktop/3. General Configuration/Search Indexing/Enable Search Indexing.cmd

Search Indexing can be configured with an option that makes it so it doesn't affect performance when you are gaming or when you are on battery.

feat(perf): respect power modes search indexing

---

src/playbook/Configuration/atlas/appx.yml
src/playbook/Executables/AtlasDesktop/3. General Configuration/Microsoft Copilot/Disable Microsoft Copilot (default).cmd
src/playbook/Executables/AtlasDesktop/3. General Configuration/Microsoft Copilot/Disable Microsoft Copilot (default).reg
src/playbook/Executables/AtlasDesktop/3. General Configuration/Microsoft Copilot/Enable Microsoft Copilot.cmd
src/playbook/Executables/AtlasModules/Scripts/wingetCheck.cmd
src/playbook/Executables/CLIENTCBS.ps1

Does these for 24H2:
- Adds support for the Copilot app
- Fixes the 'Accounts' settings page ads
- It's also more reliable generally now
- Remove & kill new Appx Teams
**This PR doesn't bring 24H2 support;** it implements needed changes I noticed when testing the Windows Insider Canary branch. These changes are required for when 24H2 is officially released, but they don't really impact 23H2.

feat: 24H2 features & fixes

---

README.md

Fix the invalid link in readme.
Solve https://github.com/orgs/Atlas-OS/discussions/1261

fix: invalid link in README.md

---

src/dependencies/local-build.ps1

fix build script for Non-English environment.
I want to test my modified version of playbook, but the output of the test target seems having a broken xml format.
It turns out that I use the Chinese environment and powershell use the Chinese encoding to read and write `playbook.conf` file, that would break the `Description` content which contains special characters.
So here is the fix, simply add `-Encoding` to the read and write commands.

fix: build script for Non-English environment

---

src/playbook/Executables/AtlasDesktop/4. Interface Tweaks/Edge Swipe/Disallow Edge Swipe.cmd

This error is faced due to an incorrect syntax used which makes the code not execute properly.
After the fix:

Fix the "ERROR: Invalid syntax." for "Disallow Edge Swipe.cmd"
