Atlas-OS/Atlas

- src/20H2/AtlasModules/atlas-config.bat
- src/20H2/Desktop/Atlas/1. Scripts/UAC/Enable UAC and Related Services.bat
I know that you can configure it as well (with that shortcut), but that does not seem to enable the two services and fully enable UAC again.
> Add enable UAC script

- src/20H2/AtlasModules/atlas-config.bat
perhaps better than nothing.
in my VMWare the environment variable "vmchk" is not set
> add a WMI VM detection

- README.md
I don't know what else I should add to this commit, but yeah, I fixed some typos, as well as some writing issues and mistakes
> Spell checking and typos on the README

- src/Desktop/Atlas/Troubleshooting/Safe Mode/Exit Safe Mode.bat
- src/Desktop/Atlas/Troubleshooting/Safe Mode/Safe Mode with Command Prompt.bat
- src/Desktop/Atlas/Troubleshooting/Safe Mode/Safe Mode with Networking.bat
- src/Desktop/Atlas/Troubleshooting/Safe Mode/Safe Mode.bat
Adds a portion to the safe mode batch files to request admin privileges for people using UAC for consistency with other batch scripts requesting UAC.
> Request UAC for Safe Mode Scripts

- src/AtlasModules/atlas-config.bat
Also removed duplicate line to disable fvevol.
> Fix Lower/Upper Filters registry key type

- .github/CONTRIBUTING.md
> Change minor things in contributing file

- .gitattributes
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/SECURITY.md
- README.md
- src/Atlas.bat
- src/Atlas.reg
- src/Desktop/Atlas/Atlas Discord.url
- src/README.md
- formal english instead of informal
- fix discord link in readme
- discord link was changed to dsc.gg/atlasos
- minor changes
> fix formatting and change formatting consistency

- README.md
- README_fr_FR.md
- README_pl_PL.md
- README_zh_CN.md
manually checked and translated. However, some words were directly checked with dictionary,
> add polish translation for the readme.md + fix formatting

- src/Desktop/Atlas/1. Install Software/Install Scoop (Must do for Software Scripts).bat
It exists twice, just under different names
> Duplicate file deleted from my recent PR

- src/AtlasModules/20H2.bat
- src/AtlasModules/atlas-config.bat
- src/AtlasModules/refreshenv.bat
made changes to the atlas-config.bat
NIC settings was not changed, reverted this part after
> small pull request of formatting, consistency and lowercase :)

- src/AtlasModules/atlas-config.bat
Added more applications to chocolatey alt software install
> Added more applications to chocolatey alt software

- src/AtlasModules/atlas-config.bat
Added the links to the webpages of which you can install Scoop/Chocolatey if the scripts do not work
> Tweaked Scoop/Chocolatey install scripts

- src/AtlasModules/atlas-config.bat
This is to prevent users from enabling UAC in the regular Windows settings with AppInfo and luafv disabled, which means that UAC completely breaks and no apps will run.
When a user tries to launch the UserAccountControlSettings executable, it is replaced by this instead:
> Add Windows UAC settings lock

- README_Translations/README_zh_CN.md
Make the translation more readable.
> Update zh-cn translation

- README.md
- README_Translations/README_id_ID.md
I just added the Indonesian translation
> Add indonesian language translation

- README.md
- translations/README.md
- translations/README_vi_VN.md
I've added Vietnamese translation for README. Please have a look.
> Added Vietnamese translation

- README.md
- translations/README_fr_FR.md
- translations/README_id_ID.md
- translations/README_pl_PL.md
- translations/README_ru_RU.md
- translations/README_zh_CN.md
All of the names have been translated to original language, the grammar or such may be incorrect but if it is please suggest what it should be instead.
> Added forum links to all README.md files

- translations/README_id_ID.md
Distinct present tense and past tense.
Change some words into familiar and standard one
Add Disclaimer translator
*Not blindy copy-paste from translator engine and call it translation
> Major Improvement

- translations/README_fr_FR.md
I have see that you have a french traduction but honestly sometimes i didn't understand the ideas behind the sentences thus i have decided to propose changes that i think are more understandable. I left some translations that are weird for me but may not be for a Canadian (in France we use a lot of English words unlike Canada which tries to translate everything into good French).
> correction du français

- .github/CONTRIBUTING.md
- translations/README_de_DE.md
- translations/README_id_ID.md
- translations/README_vi_VN.md
-Keep same format for all translators in the end of all Translation README
-Small change in the CONTRIBUTING.md
> Translation formatting

- translations/README_tr_TR.md
Turkish Translation for users.
> Turkish Translation / Türkçe Çeviri

- README.md
#504 Adding flag for Turkish translation
> Update README.md for Turkish Translation

- src/AtlasModules/atlas-config.bat
commit 790048a72913bb553df1fbdf7c6ff183aa4974e3 fixed one occurence of tcp heuristics command. here is a fix for another place.
> fix another occurence of tcp heuristics command

- README.md
- translations/README_en_US.md
Hey there y'all,
Hope ya'll are havin' a rootin' tootin' day. I'm here to propose a change to the README.md file by addin' a translation to our good ol' 'Merican language. 
Now, I know some folks might not be familiar with the technical jargons in the file, and that's why I thought it'd be a hoot to translate it into our native tongue. This'll make it easy for everyone to understand what Atlas is all about, even for those without a computer science background.
I believe this'll be a big help for the community, and I'm lookin' forward to hearin' your thoughts on this. So, let's round up and get this done!
Yeehaw!
> 'Merican Translation 

- src/README.md
It seems NTLite has dropped the `01`. This PR makes the doc more up to date.
> Remove the 01 in NLTmpMnt01

- README.md
- translations/README.md
- translations/README_sv_SE.md
Here is my Swedish translation using a bit of Swedish slang words and also normal Swedish. If there's any swedes who wants to correct me leave a comment please.
> Swedish Translation

- translations/README_es_ES.md
This refactoring does/tries to do the following:
- Gives the banner rounded corners
- Adds emojis to the titles to give the README a touch of personality and highlight certain aspects of its content
- Improves text readability
- Corrects Spanish misspellings and grammatical mistakes
- Translates some english words to existing Spanish ones
- Adds missing FAQ sections and wiki pages to the contents table with their proper translations
- Makes sure each of the hyperlinks takes you where it has to (also fixed the link to the "Windows vs. Atlas" in the table of contents as a result of adding an emoji to the title)
*Regarding the translation guide*
I have:
- Kept the disclaimer in English (I added an emoji to the title if that's ok, the translate guide didn't say anything about that)
- Kept the …
> translations: refine README_es_ES.md

- translations/README_vi_VN.md
Fix Some Grammar issues on readme_vi_VN
> Update Translation Readme

- src/AtlasModules/atlas-config.cmd
- src/Desktop/Atlas/3. Configuration/Oculus VR/Disable Oculus Services.cmd
- src/Desktop/Atlas/3. Configuration/Oculus VR/Enable Oculus Services.cmd
Leaving as a PR until multiple people can test if it works.
> Add Oculus VR Scripts

- translations/README_ar_SA.md
- translations/README_de_DE.md
- translations/README_en_GB.md
- translations/README_en_US.md
- translations/README_es_ES.md
- translations/README_fr_FR.md
- translations/README_id_ID.md
- translations/README_ph_PH.md
- translations/README_pl_PL.md
- translations/README_ru_RU.md
- translations/README_sv_SE.md
- translations/README_tr_TR.md
- translations/README_ua_UA.md
- translations/README_vi_VN.md
- translations/README_zh_CN.md
> Translation readme patch

- README.md
move latest readme to readme-remake branch
> Readme remake

- translations/README_vi_VN.md
I think the new README is here, so I updated the Vietnamese translation, replacing the poor-quality old translation
> update Vietnamese translation

- README.md
- translations/README_bs_BA.md
Both the translation itself and added bosnian to the list of languages
> Add bosnian (bosanski) translation

- translations/README_id_ID.md
Translate latest README.md to ID localization.
> Update README_id_ID.md with latest translation

- translations/README_es_ES.md
- Updated the Spanish README with the latest translation from [Origin_README.md](https://github.com/Atlas-OS/Atlas/blob/main/translations/Origin_README.md)
> translations: update Spanish README

- src/Executables/Atlas/1. Software/Install Software.ps1
> Remove 7zip entry

- README.md
- translations/README_pt_BR.md
The first commit in this language-pt_br branch added a Brazilian Portuguese translation to the README file, named tranlation/README_pt_BR.md;
In a second commit, the URLs to Microsoft's Windows License Terms page have also been modified to point to the page containing Microsoft's own version of their Windows License Terms in Brazilian Portuguese.
This resolves issue #710, opened about an hour ago.
> [ADD PT_BR README] - Brazilian Portuguese Translation to README.md

- src/Configuration/features/atlas/start.yml
> Only one type of quotation marks in start.yml

- src/Executables/Atlas/1. Software/Install Software.ps1
because apparently i cant directly push...
> feat: 📦️ add kvs

- src/Executables/Atlas/3. Configuration/1. General Configuration/Power/Hibernation/Enable Hibernation.cmd
> Update Enable Hibernation.cmd

- translations/README_translate.md
Update README_translate.md to the latest README.md, and that's all.
> docs: Update README_translate.md to latest README.md

- README.md
- translations/README_cs_CZ.md
Added Czech translation for README.md
> Added Czech translation

- README.md
- translations/README.md
- translations/README_ar_SA.md
- translations/README_bg_BG.md
- translations/README_bs_BA.md
- translations/README_cs_CZ.md
- translations/README_de_DE.md
- translations/README_es_ES.md
- translations/README_fr_FR.md
- translations/README_hi_HI.md
- translations/README_hr_HR.md
- translations/README_id_ID.md
- translations/README_it_IT.md
- translations/README_ph_PH.md
- translations/README_pl_PL.md
- translations/README_pt_BR.md
- translations/README_ru_RU.md
- translations/README_sv_SE.md
- translations/README_tr_TR.md
- translations/README_translate.md
- translations/README_ua_UA.md
- translations/README_vi_VN.md
- translations/README_zh_CN.md
> multiple changes to README and it's translation

- translations/README_vi_VN.md
+ Updated Vietnamese translation.
> Updated Vietnamese translation

- .github/workflows/apbx.yaml
- src/Configuration/features/atlas/start.yml
Fixes a YAML syntax error. No approvals will be done as it's an urgent fix.
> Fix APBX workflow

- translations/README_ko_KR.md
- [✔] Did you test your changes or double check that they work?
- [✔] Did you read and follow the [Atlas Contribution Guidelines](https://docs.atlasos.net/contributions/)?
- [❌] Did you commit to the [`dev`](https://github.com/Atlas-OS/Atlas/tree/dev) branch and not [`main`](https://github.com/Atlas-OS/Atlas)?
I rewritten the Korean translation file of the "README.md " file that was in question yesterday.
I hope there's no problem 🤣
> Korean translation of the README.md file

- README.md
- src/Configuration/features/atlas/services.yml
- src/Executables/DISABLEPNP.ps1
- src/Executables/NGEN.ps1
One of the links in the README was broken/outdated and redirected to a "404 - Not found" page.
> fix broken links in README.md

- src/playbook/Executables/Atlas/1. Software/Install Software.ps1
Describe your pull request
Fixed the sorting, so that instead of being sorted in the format:
12
34
56,
now it is sorted like:
14
25
36,
making it way easier to read since they are already sort of grouped by type.
I had to change the function for adding checkboxes into "init_items", to get the final count of items.
Feel free to change any of the function names!
Added a check at the start to use the system app theme, instead of being defaulted to white. Made the dark mode a little darker.
Also added Sharex after Lightshot, as suggested by @JayXTQ
> Update Install Software.ps1

- src/playbook/Configuration/tweaks/qol/explorer/disable-network-navigation-pane.yml
Incorrect value
Fix for Network Navigation Pane not being disabled as default.
> Navigation Pane Fix

- .github/workflows/apbx.yaml
Added a live log output for the AME wizard, this can be helpful with debugging developer playbooks.
Fixed changes from #897
> feat: AME Live Log

- README.md
Corrects the name of the Ukrainian language
> Correct the Ukrainian language name

- src/playbook/Executables/AtlasDesktop/1. Software/How To Install Software.url
- src/playbook/Executables/AtlasDesktop/2. Drivers/Driver Instructions.url
- src/playbook/Executables/AtlasDesktop/3. Configuration/Power/Timer Resolution/! Documentation.url
- src/playbook/Executables/AtlasDesktop/6. Advanced Configuration/Must Read First.url
> Fix: URL Shortcuts

- README.md
Corrects language name of the Ukrainian language
> Correct language name of Ukrainian

- translations/README_th_TH.md
**Apologize to open an additional request due to my poor check in #937**
Updated Atlas path `github-banner.png` in Thai translation to fix banner not loading properly.
> Fix banner not load properly in Thai translation of README.md

- src/playbook/playbook.conf
The "learn more" option leads to dead links. Corrected in this commit
> Fix: playbook.conf "Learn more"

- .github/ISSUE_TEMPLATE/bug_report.yml
Adding Windows 11 to the bug report so people can issue bugs for Windows 11 with ease.
> Adding Windows 11 to Bug Report

- src/playbook/Executables/AtlasDesktop/3. Configuration/Power/CPU Idle/Context Menu/Remove Idle toggle in context menu (default).reg
Fixed the Option "Remove Idle toggle in context menu". The Wrong Registry-Entry will be tried to remove.
> Fixed CPU Idle - Remove from Context menu

- translations/README_translate.md
> Fix: Readme translate got removed in #920

- src/playbook/Executables/AtlasDesktop/4. Optional Tweaks/Windows 11 Taskbar/Disable News and Interests.reg
- src/playbook/Executables/AtlasDesktop/4. Optional Tweaks/Windows 11 Taskbar/Enable News and Interests.reg
Optional scripts to enable 'Widgets' in windows 11 as well as disable back to Atlas default.
> W11 enable/disable Widgets scripts

- src/playbook/Executables/AtlasModules/Scripts/ScriptWrappers/ConfigVBS.ps1
> fix: typo in ConfigVBS.ps1

- src/playbook/Executables/AtlasModules/Scripts/ScriptWrappers/DisablePowerSaving.ps1
To fix slideshow issues with desktop and lock screen wallpaper.
Proved fixed for desktop, pending lock screen test
> fix: Slideshow wallpaper issues

- README.md
Banner link was broked (it got migrated), fixed that.
Changed the branking kit link to our docs.
> fix: broken banner, branding kit link

- src/playbook/Configuration/tweaks.yml
- src/playbook/Configuration/tweaks/qol/disable-dynamic-lighting.yml
-Disables Dynamic Lighting by default
> feat: Disable Dynamic Lighting

- src/playbook/Configuration/tweaks.yml
- src/playbook/Configuration/tweaks/qol/explorer/enable-long-paths.yml
- src/playbook/Executables/AtlasDesktop/4. Interface Tweaks/File Explorer Customization/App Icons on Thumbnails/Disable App Icons on Thumbnails.reg
- src/playbook/Executables/AtlasDesktop/4. Interface Tweaks/File Explorer Customization/App Icons on Thumbnails/Enable App Icons on Thumbnails (default).reg
-disable path length limit
-add toggle default app icon on thumbnails to the atlas folder
> feat: disable path length limit, add toggle app icons on thumbnails

- src/playbook/Executables/AtlasDesktop/6. Advanced Configuration/Driver Configuration/AutoGpuAffinity.url
> fix: update AutoGPUAffinity url

- src/playbook/Configuration/tweaks.yml
- src/playbook/Configuration/tweaks/qol/explorer/remove-context-menus/extract-all.yml
- src/playbook/Configuration/tweaks/qol/explorer/remove-context-menus/extract.yml
- src/playbook/Executables/AtlasDesktop/4. Interface Tweaks/Context Menus/Extract/Add Extract.reg
- src/playbook/Executables/AtlasDesktop/4. Interface Tweaks/Context Menus/Extract/Remove Extract (default).reg
-hide "extract" and "extract all" options completely
-add toggle in the atlas folder
> fix: completely hide extract, add toggle in atlas folder

- src/playbook/Executables/AtlasModules/Scripts/ScriptWrappers/InstallSoftware.ps1
added powershell 7 to install software script
> feat: add powershell 7 to install software script

- src/playbook/Executables/AtlasDesktop/2. Drivers/Run Update Drivers.cmd
- src/playbook/Executables/AtlasModules/Scripts/ScriptWrappers/UpdateDrivers.ps1
Completes https://github.com/orgs/Atlas-OS/projects/7?pane=issue&itemId=70790980
This is to me and @TheyCreeper's interpretation of what the feature suggests.
Remake because the last one was an absolute mess.
> feat: update drivers through windows update
